import { Sparkles } from "lucide-react";

export function StatCard({
  icon: Icon,
  label,
  value,
  trend,
  tone = "primary",
}) {
  const tones = {
    primary: "bg-blue-100 text-blue-600",
    success: "bg-green-100 text-green-600",
    warning: "bg-yellow-100 text-yellow-600",
    emergency: "bg-red-100 text-red-600",
    accent: "bg-purple-100 text-purple-600",
  };

  return (
    <div className="rounded-2xl border border-gray-200 bg-white p-5 shadow-sm hover:shadow-md transition">
      <div className="flex items-center justify-between">
        <span
          className={`flex h-10 w-10 items-center justify-center rounded-xl ${tones[tone]}`}
        >
          <Icon className="h-5 w-5" />
        </span>

        {trend && (
          <span className="text-xs font-medium text-green-600">
            {trend}
          </span>
        )}
      </div>

      <p className="mt-4 text-3xl font-bold">
        {value}
      </p>

      <p className="mt-1 text-sm text-gray-500">
        {label}
      </p>
    </div>
  );
}

export default function SummaryCard({
  title = "AI Situation Summary",
  body,
  items,
}) {
  return (
    <div className="relative overflow-hidden rounded-2xl border border-blue-200 bg-white p-6 shadow-sm">

      {/* Background Glow */}
      <div className="absolute -right-16 -top-16 h-48 w-48 rounded-full bg-blue-100 blur-3xl opacity-60" />

      <div className="relative">

        {/* Header */}
        <div className="flex items-center gap-3">

          <span className="flex h-10 w-10 items-center justify-center rounded-xl bg-blue-100 text-blue-600">
            <Sparkles className="h-5 w-5" />
          </span>

          <div>
            <h3 className="font-semibold">
              {title}
            </h3>

            <p className="text-xs text-gray-500">
              Generated by Gemini AI
            </p>
          </div>

        </div>

        {/* Summary */}
        <p className="mt-4 leading-relaxed text-gray-700">
          {body}
        </p>

        {/* Statistics */}
        {items && (
          <div className="mt-5 grid grid-cols-3 gap-4 border-t pt-4">

            {items.map((item) => (
              <div key={item.label}>
                <p className="text-xl font-bold">
                  {item.value}
                </p>

                <p className="text-xs text-gray-500">
                  {item.label}
                </p>
              </div>
            ))}

          </div>
        )}

      </div>

    </div>
  );
}